apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clams-ci
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/davgordo/clams-openshift.git"
    path: clams-demo
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: clams-ci
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m